// ============================================================
// femtopll.v
// Simulation-safe wrapper for ICE40 PLL
// ============================================================

`ifndef SIMULATION

/* 
 * Do not edit this file, it was generated by gen_pll.sh
 * 
 *   FPGA kind      : ICE40
 *   Input frequency: 12 MHz
 */

module femtoPLL #(
    parameter freq = 40
) (
    input  wire pclk,
    output wire clk
);

    SB_PLL40_CORE pll (
        .REFERENCECLK (pclk),
        .PLLOUTCORE   (clk),
        .RESETB       (1'b1),
        .BYPASS       (1'b0)
    );

    defparam pll.FEEDBACK_PATH = "SIMPLE";
    defparam pll.PLLOUT_SELECT = "GENCLK";

    generate
        case (freq)

            12: begin
                defparam pll.DIVR         = 4'b0000;
                defparam pll.DIVF         = 7'b0000000;
                defparam pll.DIVQ         = 3'b000;
                defparam pll.FILTER_RANGE = 3'b001;
            end

            16: begin
                defparam pll.DIVR         = 4'b0000;
                defparam pll.DIVF         = 7'b1010100;
                defparam pll.DIVQ         = 3'b110;
                defparam pll.FILTER_RANGE = 3'b001;
            end

            20: begin
                defparam pll.DIVR         = 4'b0000;
                defparam pll.DIVF         = 7'b0110100;
                defparam pll.DIVQ         = 3'b101;
                defparam pll.FILTER_RANGE = 3'b001;
            end

            24: begin
                defparam pll.DIVR         = 4'b0000;
                defparam pll.DIVF         = 7'b0111111;
                defparam pll.DIVQ         = 3'b101;
                defparam pll.FILTER_RANGE = 3'b001;
            end

            25: begin
                defparam pll.DIVR         = 4'b0000;
                defparam pll.DIVF         = 7'b1000010;
                defparam pll.DIVQ         = 3'b101;
                defparam pll.FILTER_RANGE = 3'b001;
            end

            30: begin
                defparam pll.DIVR         = 4'b0000;
                defparam pll.DIVF         = 7'b1001111;
                defparam pll.DIVQ         = 3'b101;
                defparam pll.FILTER_RANGE = 3'b001;
            end

            35: begin
                defparam pll.DIVR         = 4'b0000;
                defparam pll.DIVF         = 7'b0101110;
                defparam pll.DIVQ         = 3'b100;
                defparam pll.FILTER_RANGE = 3'b001;
            end

            40: begin
                defparam pll.DIVR         = 4'b0000;
                defparam pll.DIVF         = 7'b0110100;
                defparam pll.DIVQ         = 3'b100;
                defparam pll.FILTER_RANGE = 3'b001;
            end

            default: begin
                // Unsupported frequency
            end

        endcase
    endgenerate

endmodule

`else
// ============================================================
// SIMULATION VERSION (NO FPGA PRIMITIVES)
// ============================================================

module femtoPLL #(
    parameter freq = 40
) (
    input  wire pclk,
    output wire clk
);
    // In simulation, bypass PLL
    assign clk = pclk;
endmodule

`endif

